export const ERROR_MOVIES = "ERROR_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const LOADING_MOVIES = "LOADING_MOVIES";
export const ADD_CURRENT_ID = "ADD_CURRENT_ID";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
